<?php
/**
 * Curated Evolution Live popular games seed.
 * Images are stored outside PHP source under /uploads/game_icons/evolution-live/.
 */
return array(
    array(
        'game_name' => 'Crazy Time',
        'api_game_id' => '917c0c51d248c33eb058e3210a2e7371',
        'api_game_code' => '917c0c51d248c33eb058e3210a2e7371',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/crazy-time.webp',
        'sort_order' => 0,
    ),
    array(
        'game_name' => 'Crazy Time A',
        'api_game_id' => '814aa56348ac4165588f2a3e251f8732',
        'api_game_code' => '814aa56348ac4165588f2a3e251f8732',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/crazy-time-a.webp',
        'sort_order' => 1,
    ),
    array(
        'game_name' => 'Crazy Coin Flip',
        'api_game_id' => 'c177ce05258ed2dcbdece64434eaf817',
        'api_game_code' => 'c177ce05258ed2dcbdece64434eaf817',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/crazy-coin-flip.webp',
        'sort_order' => 2,
    ),
    array(
        'game_name' => 'Funky Time',
        'api_game_id' => '8405541014f364b7dc59657aa6892446',
        'api_game_code' => '8405541014f364b7dc59657aa6892446',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/funky-time.webp',
        'sort_order' => 3,
    ),
    array(
        'game_name' => 'Monopoly Live',
        'api_game_id' => 'd496ac5fd91702331133e44b6bd12b26',
        'api_game_code' => 'd496ac5fd91702331133e44b6bd12b26',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/monopoly-live.webp',
        'sort_order' => 4,
    ),
    array(
        'game_name' => 'Monopoly Big Baller',
        'api_game_id' => '067806e82742ca16bfffe70f76215647',
        'api_game_code' => '067806e82742ca16bfffe70f76215647',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/monopoly-big-baller.webp',
        'sort_order' => 5,
    ),
    array(
        'game_name' => 'Mega Ball',
        'api_game_id' => '3955853fc6a0b53f7f9b9cff0be19cb8',
        'api_game_code' => '3955853fc6a0b53f7f9b9cff0be19cb8',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/mega-ball.webp',
        'sort_order' => 6,
    ),
    array(
        'game_name' => 'Dream Catcher',
        'api_game_id' => '7f50a6fbfcd9257299303b5757d43525',
        'api_game_code' => '7f50a6fbfcd9257299303b5757d43525',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/dream-catcher.webp',
        'sort_order' => 7,
    ),
    array(
        'game_name' => 'Cash or Crash',
        'api_game_id' => 'b53a604877024ef2eab9946898e65d6b',
        'api_game_code' => 'b53a604877024ef2eab9946898e65d6b',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/cash-or-crash.webp',
        'sort_order' => 8,
    ),
    array(
        'game_name' => 'Deal or No Deal',
        'api_game_id' => 'bee6be84ab995f2040f4e575c2cc3910',
        'api_game_code' => 'bee6be84ab995f2040f4e575c2cc3910',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/deal-or-no-deal.webp',
        'sort_order' => 9,
    ),
    array(
        'game_name' => 'Dead or Alive: Saloon',
        'api_game_id' => 'eda1a2c5edb8370f8df58dcf8e1381b9',
        'api_game_code' => 'eda1a2c5edb8370f8df58dcf8e1381b9',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/dead-or-alive-saloon.webp',
        'sort_order' => 10,
    ),
    array(
        'game_name' => 'Gonzo\'s Treasure Hunt',
        'api_game_id' => 'e1969a739eb17b9e7d97835357a30082',
        'api_game_code' => 'e1969a739eb17b9e7d97835357a30082',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/gonzo-s-treasure-hunt.webp',
        'sort_order' => 11,
    ),
    array(
        'game_name' => 'Gonzo\'s Treasure Map',
        'api_game_id' => '3f0b35e91f18915f5c5e88f3e1daf66e',
        'api_game_code' => '3f0b35e91f18915f5c5e88f3e1daf66e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/gonzo-s-treasure-map.webp',
        'sort_order' => 12,
    ),
    array(
        'game_name' => 'Lightning Roulette',
        'api_game_id' => '4a858d6b74c05260d3ea2762838798c7',
        'api_game_code' => '4a858d6b74c05260d3ea2762838798c7',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/lightning-roulette.webp',
        'sort_order' => 13,
    ),
    array(
        'game_name' => 'XXXtreme Lightning Roulette',
        'api_game_id' => '394fe6a2cde24bc487767236cc6eccd6',
        'api_game_code' => '394fe6a2cde24bc487767236cc6eccd6',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/xxxtreme-lightning-roulette.webp',
        'sort_order' => 14,
    ),
    array(
        'game_name' => 'Auto Lightning Roulette',
        'api_game_id' => 'd1365619bb9e9126b8ee9cbabb268853',
        'api_game_code' => 'd1365619bb9e9126b8ee9cbabb268853',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/auto-lightning-roulette.webp',
        'sort_order' => 15,
    ),
    array(
        'game_name' => 'Speed Roulette',
        'api_game_id' => 'b4af506243cafae52908e8fa266f8ff6',
        'api_game_code' => 'b4af506243cafae52908e8fa266f8ff6',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-roulette.webp',
        'sort_order' => 16,
    ),
    array(
        'game_name' => 'Roulette',
        'api_game_id' => 'c9020da3ac9119910b7146416d5a9850',
        'api_game_code' => 'c9020da3ac9119910b7146416d5a9850',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/roulette.webp',
        'sort_order' => 17,
    ),
    array(
        'game_name' => 'VIP Roulette',
        'api_game_id' => 'e8f217c3d554285933cb67072c897fac',
        'api_game_code' => 'e8f217c3d554285933cb67072c897fac',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/vip-roulette.webp',
        'sort_order' => 18,
    ),
    array(
        'game_name' => 'American Roulette',
        'api_game_id' => '0afb35f8abd269ca0c0c65a49d5145db',
        'api_game_code' => '0afb35f8abd269ca0c0c65a49d5145db',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/american-roulette.webp',
        'sort_order' => 19,
    ),
    array(
        'game_name' => 'Instant Roulette',
        'api_game_id' => 'ec65c22981a707736871eecfca8e5e25',
        'api_game_code' => 'ec65c22981a707736871eecfca8e5e25',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/instant-roulette.webp',
        'sort_order' => 20,
    ),
    array(
        'game_name' => 'Immersive Roulette',
        'api_game_id' => '3b43390eebe1f1a84b15f1251a253b24',
        'api_game_code' => '3b43390eebe1f1a84b15f1251a253b24',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/immersive-roulette.webp',
        'sort_order' => 21,
    ),
    array(
        'game_name' => 'Auto-Roulette',
        'api_game_id' => 'ed9e15ea8a2cbb9e7ad2604819764d43',
        'api_game_code' => 'ed9e15ea8a2cbb9e7ad2604819764d43',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/auto-roulette.webp',
        'sort_order' => 22,
    ),
    array(
        'game_name' => 'Auto-Roulette VIP',
        'api_game_id' => '367c395a50d4ef9edda332e17094670b',
        'api_game_code' => '367c395a50d4ef9edda332e17094670b',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/auto-roulette-vip.webp',
        'sort_order' => 23,
    ),
    array(
        'game_name' => 'Speed Auto Roulette',
        'api_game_id' => '1ffeecc77f75d0485e83036269fd9401',
        'api_game_code' => '1ffeecc77f75d0485e83036269fd9401',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-auto-roulette.webp',
        'sort_order' => 24,
    ),
    array(
        'game_name' => 'Double Ball Roulette',
        'api_game_id' => 'fae08e8e222f162b27a2d5c4329d1044',
        'api_game_code' => 'fae08e8e222f162b27a2d5c4329d1044',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/double-ball-roulette.webp',
        'sort_order' => 25,
    ),
    array(
        'game_name' => 'Red Door Roulette',
        'api_game_id' => '6ddd73419e9a49b6b942e29088219d64',
        'api_game_code' => '6ddd73419e9a49b6b942e29088219d64',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/red-door-roulette.webp',
        'sort_order' => 26,
    ),
    array(
        'game_name' => 'Roleta Ao Vivo',
        'api_game_id' => '7476b40db4af067e4d00fa2dd2067ef9',
        'api_game_code' => '7476b40db4af067e4d00fa2dd2067ef9',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/roleta-ao-vivo.webp',
        'sort_order' => 27,
    ),
    array(
        'game_name' => 'French Roulette Gold',
        'api_game_id' => '36b1e71c6f51827e24261d06a22b1e31',
        'api_game_code' => '36b1e71c6f51827e24261d06a22b1e31',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/french-roulette-gold.webp',
        'sort_order' => 28,
    ),
    array(
        'game_name' => 'Dragonara Roulette',
        'api_game_id' => '565e25c35f0b387631ec71505a68bac3',
        'api_game_code' => '565e25c35f0b387631ec71505a68bac3',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/dragonara-roulette.webp',
        'sort_order' => 29,
    ),
    array(
        'game_name' => 'Lightning Baccarat',
        'api_game_id' => '0f78172e62af19dcc9c75077ea0d0cd0',
        'api_game_code' => '0f78172e62af19dcc9c75077ea0d0cd0',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/lightning-baccarat.webp',
        'sort_order' => 30,
    ),
    array(
        'game_name' => 'Baccarat Squeeze',
        'api_game_id' => '83441043af47abb22828010c8d882d6a',
        'api_game_code' => '83441043af47abb22828010c8d882d6a',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/baccarat-squeeze.webp',
        'sort_order' => 31,
    ),
    array(
        'game_name' => 'Baccarat A',
        'api_game_id' => '1d955d48d50aef2e9546466d9d859be1',
        'api_game_code' => '1d955d48d50aef2e9546466d9d859be1',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/baccarat-a.webp',
        'sort_order' => 32,
    ),
    array(
        'game_name' => 'Baccarat B',
        'api_game_id' => '0ea8519b837ebd62f5a8978acca33e1d',
        'api_game_code' => '0ea8519b837ebd62f5a8978acca33e1d',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/baccarat-b.webp',
        'sort_order' => 33,
    ),
    array(
        'game_name' => 'Baccarat C',
        'api_game_id' => '21cf3fdf28915845ff76f963695bb8e3',
        'api_game_code' => '21cf3fdf28915845ff76f963695bb8e3',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/baccarat-c.webp',
        'sort_order' => 34,
    ),
    array(
        'game_name' => 'Baccarat Control Squeeze',
        'api_game_id' => '1c120a3aaf113cb484d3fb83f7e4efa3',
        'api_game_code' => '1c120a3aaf113cb484d3fb83f7e4efa3',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/baccarat-control-squeeze.webp',
        'sort_order' => 35,
    ),
    array(
        'game_name' => 'Bac Bo',
        'api_game_id' => '9b25f8d744859c6840d16ff6103dc5a6',
        'api_game_code' => '9b25f8d744859c6840d16ff6103dc5a6',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/bac-bo.webp',
        'sort_order' => 36,
    ),
    array(
        'game_name' => 'Speed Baccarat A',
        'api_game_id' => 'ca432917c1beafa247d346bdc7c178a7',
        'api_game_code' => 'ca432917c1beafa247d346bdc7c178a7',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-a.webp',
        'sort_order' => 37,
    ),
    array(
        'game_name' => 'Speed Baccarat B',
        'api_game_id' => 'd3c71b0de6799ca7419d1e7834a05a47',
        'api_game_code' => 'd3c71b0de6799ca7419d1e7834a05a47',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-b.webp',
        'sort_order' => 38,
    ),
    array(
        'game_name' => 'Speed Baccarat C',
        'api_game_id' => '78a8f259b57a85b7c01f9a1c5c667898',
        'api_game_code' => '78a8f259b57a85b7c01f9a1c5c667898',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-c.webp',
        'sort_order' => 39,
    ),
    array(
        'game_name' => 'Speed Baccarat D',
        'api_game_id' => '441f7d75f645a3ba8c6ca6ac97766e27',
        'api_game_code' => '441f7d75f645a3ba8c6ca6ac97766e27',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-d.webp',
        'sort_order' => 40,
    ),
    array(
        'game_name' => 'Speed Baccarat E',
        'api_game_id' => 'b565bd61b2dd5216d910bd07feb5994e',
        'api_game_code' => 'b565bd61b2dd5216d910bd07feb5994e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-e.webp',
        'sort_order' => 41,
    ),
    array(
        'game_name' => 'Speed Baccarat F',
        'api_game_id' => 'b332c47c868946659d7de97f4157bdb3',
        'api_game_code' => 'b332c47c868946659d7de97f4157bdb3',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-f.webp',
        'sort_order' => 42,
    ),
    array(
        'game_name' => 'Speed Baccarat G',
        'api_game_id' => '0f318059268a7522710dfa4b867005e9',
        'api_game_code' => '0f318059268a7522710dfa4b867005e9',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-g.webp',
        'sort_order' => 43,
    ),
    array(
        'game_name' => 'Speed Baccarat H',
        'api_game_id' => '08e3fac9968542e243e1b320c033b8d7',
        'api_game_code' => '08e3fac9968542e243e1b320c033b8d7',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-h.webp',
        'sort_order' => 44,
    ),
    array(
        'game_name' => 'Speed Baccarat I',
        'api_game_id' => '306416e24dc7aa7400ae46d151c3526e',
        'api_game_code' => '306416e24dc7aa7400ae46d151c3526e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-i.webp',
        'sort_order' => 45,
    ),
    array(
        'game_name' => 'Speed Baccarat J',
        'api_game_id' => 'fbd7f3f9692774963341d7758aa0f439',
        'api_game_code' => 'fbd7f3f9692774963341d7758aa0f439',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-j.webp',
        'sort_order' => 46,
    ),
    array(
        'game_name' => 'Speed Baccarat K',
        'api_game_id' => '04bbac98e29afadca20019f21b2c21d2',
        'api_game_code' => '04bbac98e29afadca20019f21b2c21d2',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-k.webp',
        'sort_order' => 47,
    ),
    array(
        'game_name' => 'Speed Baccarat L',
        'api_game_id' => '5c58dcfb54df086d00b8725a10761e03',
        'api_game_code' => '5c58dcfb54df086d00b8725a10761e03',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-l.webp',
        'sort_order' => 48,
    ),
    array(
        'game_name' => 'Speed Baccarat M',
        'api_game_id' => '47a936ba7665516ecf132a2b8898b2eb',
        'api_game_code' => '47a936ba7665516ecf132a2b8898b2eb',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-m.webp',
        'sort_order' => 49,
    ),
    array(
        'game_name' => 'Speed Baccarat N',
        'api_game_id' => '374b0298147823425fb0d41a6fae25ba',
        'api_game_code' => '374b0298147823425fb0d41a6fae25ba',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-n.webp',
        'sort_order' => 50,
    ),
    array(
        'game_name' => 'Speed Baccarat O',
        'api_game_id' => '964e7d090167c429e1b6c15a97210e22',
        'api_game_code' => '964e7d090167c429e1b6c15a97210e22',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-o.webp',
        'sort_order' => 51,
    ),
    array(
        'game_name' => 'Speed Baccarat P',
        'api_game_id' => 'cb6e4ad80df2c456cc69d7d43400ef2a',
        'api_game_code' => 'cb6e4ad80df2c456cc69d7d43400ef2a',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-p.webp',
        'sort_order' => 52,
    ),
    array(
        'game_name' => 'Speed Baccarat Q',
        'api_game_id' => '85e9ebaaec03ab8d1e579cf2d28a898e',
        'api_game_code' => '85e9ebaaec03ab8d1e579cf2d28a898e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-q.webp',
        'sort_order' => 53,
    ),
    array(
        'game_name' => 'Speed Baccarat R',
        'api_game_id' => '44eca39b0a839bf2af75db7a5ecb3450',
        'api_game_code' => '44eca39b0a839bf2af75db7a5ecb3450',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-r.webp',
        'sort_order' => 54,
    ),
    array(
        'game_name' => 'Speed Baccarat S',
        'api_game_id' => '3c4df047efd6126b12f351ad40123e40',
        'api_game_code' => '3c4df047efd6126b12f351ad40123e40',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-s.webp',
        'sort_order' => 55,
    ),
    array(
        'game_name' => 'Speed Baccarat T',
        'api_game_id' => '60c61989f6a8ff1a33b14c98abe83e62',
        'api_game_code' => '60c61989f6a8ff1a33b14c98abe83e62',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-t.webp',
        'sort_order' => 56,
    ),
    array(
        'game_name' => 'Speed Baccarat U',
        'api_game_id' => 'e0e8f76fa25eb2fcebf96e7b5f45e120',
        'api_game_code' => 'e0e8f76fa25eb2fcebf96e7b5f45e120',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-u.webp',
        'sort_order' => 57,
    ),
    array(
        'game_name' => 'Speed Baccarat V',
        'api_game_id' => 'ce7558886d46f01a02aade95a5127b43',
        'api_game_code' => 'ce7558886d46f01a02aade95a5127b43',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-v.webp',
        'sort_order' => 58,
    ),
    array(
        'game_name' => 'Speed Baccarat W',
        'api_game_id' => '239ca8da8e291b7d9e377adfcf4745dc',
        'api_game_code' => '239ca8da8e291b7d9e377adfcf4745dc',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-w.webp',
        'sort_order' => 59,
    ),
    array(
        'game_name' => 'Speed Baccarat X',
        'api_game_id' => '128268adb0c5c9cd62746a0a8105dc21',
        'api_game_code' => '128268adb0c5c9cd62746a0a8105dc21',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-x.webp',
        'sort_order' => 60,
    ),
    array(
        'game_name' => 'Speed Baccarat Z',
        'api_game_id' => '52a7b9d8c127b8b33f5c8d682ed40371',
        'api_game_code' => '52a7b9d8c127b8b33f5c8d682ed40371',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/speed-baccarat-z.webp',
        'sort_order' => 61,
    ),
    array(
        'game_name' => 'Peek Baccarat',
        'api_game_id' => 'c367b8269a44719f19d7264b37d4582b',
        'api_game_code' => 'c367b8269a44719f19d7264b37d4582b',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/peek-baccarat.webp',
        'sort_order' => 62,
    ),
    array(
        'game_name' => 'No Commission Baccarat',
        'api_game_id' => '17440e0b64775115bb5ae6554a2973a9',
        'api_game_code' => '17440e0b64775115bb5ae6554a2973a9',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/no-commission-baccarat.webp',
        'sort_order' => 63,
    ),
    array(
        'game_name' => 'No Commission Speed Baccarat A',
        'api_game_id' => 'b82371488f8fb90efb946634ac61d7f5',
        'api_game_code' => 'b82371488f8fb90efb946634ac61d7f5',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/no-commission-speed-baccarat-a.webp',
        'sort_order' => 64,
    ),
    array(
        'game_name' => 'No Commission Speed Baccarat B',
        'api_game_id' => '7f5b0d20c3f491c4fc9456e951ea7005',
        'api_game_code' => '7f5b0d20c3f491c4fc9456e951ea7005',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/no-commission-speed-baccarat-b.webp',
        'sort_order' => 65,
    ),
    array(
        'game_name' => 'No Commission Speed Baccarat C',
        'api_game_id' => 'f9e106cfc932d1f0fdb0cc3dd1057c1a',
        'api_game_code' => 'f9e106cfc932d1f0fdb0cc3dd1057c1a',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/no-commission-speed-baccarat-c.webp',
        'sort_order' => 66,
    ),
    array(
        'game_name' => 'Super Sic Bo',
        'api_game_id' => 'e3951a5bf624e822a22cba1cbe619df5',
        'api_game_code' => 'e3951a5bf624e822a22cba1cbe619df5',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/super-sic-bo.webp',
        'sort_order' => 67,
    ),
    array(
        'game_name' => 'Emperor Sic Bo',
        'api_game_id' => '6a1e55dc7a14f038d9b0207fdb3ecbc0',
        'api_game_code' => '6a1e55dc7a14f038d9b0207fdb3ecbc0',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/emperor-sic-bo.webp',
        'sort_order' => 68,
    ),
    array(
        'game_name' => 'Craps',
        'api_game_id' => '689dd8e8f17dae910dba9fdd4990d41e',
        'api_game_code' => '689dd8e8f17dae910dba9fdd4990d41e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/craps.webp',
        'sort_order' => 69,
    ),
    array(
        'game_name' => 'Fan Tan',
        'api_game_id' => '5cb6aa4e2ce1c775c568561401ffdfca',
        'api_game_code' => '5cb6aa4e2ce1c775c568561401ffdfca',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/fan-tan.webp',
        'sort_order' => 70,
    ),
    array(
        'game_name' => 'Dragon Tiger',
        'api_game_id' => '1fd20a344c9f147cdef85bbaa7447dcd',
        'api_game_code' => '1fd20a344c9f147cdef85bbaa7447dcd',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/dragon-tiger.webp',
        'sort_order' => 71,
    ),
    array(
        'game_name' => 'Emperor Dragon Tiger',
        'api_game_id' => '1eaa16200ee75bddd50ab54b01fbefa9',
        'api_game_code' => '1eaa16200ee75bddd50ab54b01fbefa9',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/emperor-dragon-tiger.webp',
        'sort_order' => 72,
    ),
    array(
        'game_name' => 'Teen Patti',
        'api_game_id' => '0617a82334f4f1766cf282ce906e1df7',
        'api_game_code' => '0617a82334f4f1766cf282ce906e1df7',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/teen-patti.webp',
        'sort_order' => 73,
    ),
    array(
        'game_name' => 'Super Andar Bahar',
        'api_game_id' => 'f7b98e899461bdd49f92afc36b4c0db5',
        'api_game_code' => 'f7b98e899461bdd49f92afc36b4c0db5',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/super-andar-bahar.webp',
        'sort_order' => 74,
    ),
    array(
        'game_name' => 'Football Studio',
        'api_game_id' => '392e13e38b3cec5ad259254a206d343a',
        'api_game_code' => '392e13e38b3cec5ad259254a206d343a',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/football-studio.webp',
        'sort_order' => 75,
    ),
    array(
        'game_name' => 'Football Studio Dice',
        'api_game_id' => '1909b4e3380dc37654f8e3997e63ec1b',
        'api_game_code' => '1909b4e3380dc37654f8e3997e63ec1b',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/football-studio-dice.webp',
        'sort_order' => 76,
    ),
    array(
        'game_name' => 'Side Bet City',
        'api_game_id' => '1a0fa4ddcf2dafef402cd3aeb693edba',
        'api_game_code' => '1a0fa4ddcf2dafef402cd3aeb693edba',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/side-bet-city.webp',
        'sort_order' => 77,
    ),
    array(
        'game_name' => 'Casino Hold\'em',
        'api_game_id' => '8cb4d1c55915742a45f59f2adbb97e24',
        'api_game_code' => '8cb4d1c55915742a45f59f2adbb97e24',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/casino-hold-em.webp',
        'sort_order' => 78,
    ),
    array(
        'game_name' => 'Caribbean Stud Poker',
        'api_game_id' => '724eebd5cbe7555b01ed60279cb59e5a',
        'api_game_code' => '724eebd5cbe7555b01ed60279cb59e5a',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/caribbean-stud-poker.webp',
        'sort_order' => 79,
    ),
    array(
        'game_name' => 'Extreme Texas Hold\'em',
        'api_game_id' => 'fc4e71748bc1a8a7abfc4c1e2f63aa3b',
        'api_game_code' => 'fc4e71748bc1a8a7abfc4c1e2f63aa3b',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/extreme-texas-hold-em.webp',
        'sort_order' => 80,
    ),
    array(
        'game_name' => 'Texas Hold\'em Bonus Poker',
        'api_game_id' => '0d743830cca897a7c4c9187bc7f9b812',
        'api_game_code' => '0d743830cca897a7c4c9187bc7f9b812',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/texas-hold-em-bonus-poker.webp',
        'sort_order' => 81,
    ),
    array(
        'game_name' => 'Triple Card Poker',
        'api_game_id' => 'b7c3b022f1c2b768524523d855a58d89',
        'api_game_code' => 'b7c3b022f1c2b768524523d855a58d89',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/triple-card-poker.webp',
        'sort_order' => 82,
    ),
    array(
        'game_name' => 'Blackjack A',
        'api_game_id' => 'e7df9c2fdf7c680ddee3739f5b703c88',
        'api_game_code' => 'e7df9c2fdf7c680ddee3739f5b703c88',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-a.webp',
        'sort_order' => 83,
    ),
    array(
        'game_name' => 'Blackjack B',
        'api_game_id' => '5344ba3dbbd1b3c4b0082fe6212d502c',
        'api_game_code' => '5344ba3dbbd1b3c4b0082fe6212d502c',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-b.webp',
        'sort_order' => 84,
    ),
    array(
        'game_name' => 'Blackjack C',
        'api_game_id' => '135c1d0063a5a18532314e7f669da0a2',
        'api_game_code' => '135c1d0063a5a18532314e7f669da0a2',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-c.webp',
        'sort_order' => 85,
    ),
    array(
        'game_name' => 'Power Blackjack',
        'api_game_id' => '1d1c0d3ec98deb128bdd5acdef0f157e',
        'api_game_code' => '1d1c0d3ec98deb128bdd5acdef0f157e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/power-blackjack.webp',
        'sort_order' => 86,
    ),
    array(
        'game_name' => 'Infinite Blackjack',
        'api_game_id' => '58d7089aa20bce7f70e0e2ce81e888f4',
        'api_game_code' => '58d7089aa20bce7f70e0e2ce81e888f4',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/infinite-blackjack.webp',
        'sort_order' => 87,
    ),
    array(
        'game_name' => 'Blackjack Party',
        'api_game_id' => 'd609730e8da3693bd8ac428926747390',
        'api_game_code' => 'd609730e8da3693bd8ac428926747390',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-party.webp',
        'sort_order' => 88,
    ),
    array(
        'game_name' => 'Blackjack VIP A',
        'api_game_id' => '555681ca33cd74847afbab62a9c446a3',
        'api_game_code' => '555681ca33cd74847afbab62a9c446a3',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-a.webp',
        'sort_order' => 89,
    ),
    array(
        'game_name' => 'Blackjack VIP B',
        'api_game_id' => '446551dd9ae32002824b065e57686463',
        'api_game_code' => '446551dd9ae32002824b065e57686463',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-b.webp',
        'sort_order' => 90,
    ),
    array(
        'game_name' => 'Blackjack VIP C',
        'api_game_id' => '68c5eb853ecdfee94cd5a22f3210aacf',
        'api_game_code' => '68c5eb853ecdfee94cd5a22f3210aacf',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-c.webp',
        'sort_order' => 91,
    ),
    array(
        'game_name' => 'Blackjack VIP D',
        'api_game_id' => 'd3cc53709c12b63755a2e40bba47f448',
        'api_game_code' => 'd3cc53709c12b63755a2e40bba47f448',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-d.webp',
        'sort_order' => 92,
    ),
    array(
        'game_name' => 'Blackjack VIP E',
        'api_game_id' => '2c2f06025f65fe745cabd81a3aae8aba',
        'api_game_code' => '2c2f06025f65fe745cabd81a3aae8aba',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-e.webp',
        'sort_order' => 93,
    ),
    array(
        'game_name' => 'Blackjack VIP 1',
        'api_game_id' => '9f509cdc3cdce669368977eda1588011',
        'api_game_code' => '9f509cdc3cdce669368977eda1588011',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-1.webp',
        'sort_order' => 94,
    ),
    array(
        'game_name' => 'Blackjack VIP 2',
        'api_game_id' => '7530ac3d1140882df7e883641237bb42',
        'api_game_code' => '7530ac3d1140882df7e883641237bb42',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-vip-2.webp',
        'sort_order' => 95,
    ),
    array(
        'game_name' => 'Blackjack Diamond VIP',
        'api_game_id' => '7d4e80750fdbd046e210dc8e1d1a0c21',
        'api_game_code' => '7d4e80750fdbd046e210dc8e1d1a0c21',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-diamond-vip.webp',
        'sort_order' => 96,
    ),
    array(
        'game_name' => 'Blackjack Platinum VIP',
        'api_game_id' => 'c2bd2aafaa4dbaff9df0cd0b53fc6056',
        'api_game_code' => 'c2bd2aafaa4dbaff9df0cd0b53fc6056',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/blackjack-platinum-vip.webp',
        'sort_order' => 97,
    ),
    array(
        'game_name' => 'First Person Roulette',
        'api_game_id' => 'a82670530f49a6b3445dc1a592a2eb9e',
        'api_game_code' => 'a82670530f49a6b3445dc1a592a2eb9e',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/first-person-roulette.webp',
        'sort_order' => 98,
    ),
    array(
        'game_name' => 'First Person Baccarat',
        'api_game_id' => 'e18dfa4a5dd4a0f2d8b45337bd6abb9d',
        'api_game_code' => 'e18dfa4a5dd4a0f2d8b45337bd6abb9d',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/first-person-baccarat.webp',
        'sort_order' => 99,
    ),
    array(
        'game_name' => 'First Person Dream Catcher',
        'api_game_id' => '7ee0da50996278d7fe5136f86f368fa5',
        'api_game_code' => '7ee0da50996278d7fe5136f86f368fa5',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/first-person-dream-catcher.webp',
        'sort_order' => 100,
    ),
    array(
        'game_name' => 'First Person Dragon Tiger',
        'api_game_id' => '4b4c45709dfd8188d7d6d12fae15bd42',
        'api_game_code' => '4b4c45709dfd8188d7d6d12fae15bd42',
        'api_vendor_code' => 'evolutionlive',
        'api_provider_name' => 'Evolution Live',
        'provider_id' => '58',
        'category' => 'CasinoLive',
        'api_game_type' => 'CasinoLive',
        'image' => '/uploads/game_icons/evolution-live/first-person-dragon-tiger.webp',
        'sort_order' => 101,
    ),
);
