<?php
return array(
    array('local_game_uid' => '', 'provider_game_code' => 'aviator', 'game_name' => 'Aviator', 'api_game_id' => 'a04d1f3eb8ccec8a4823bdf18e3f0e84', 'api_game_code' => 'aviator', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'dice', 'game_name' => 'Dice', 'api_game_id' => '8a87aae7a3624d284306e9c6fe1b3e9c', 'api_game_code' => 'dice', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'goal', 'game_name' => 'Goal', 'api_game_id' => 'c68a515f0b3b10eec96cf6d33299f4e2', 'api_game_code' => 'goal', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'hi-lo', 'game_name' => 'Hi Lo', 'api_game_id' => 'a669c993b0e1f1b7da100fcf95516bdf', 'api_game_code' => 'hi-lo', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'hotline', 'game_name' => 'Hotline', 'api_game_id' => 'b31720b3cd65d917a1a96ef61a72b672', 'api_game_code' => 'hotline', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'keno', 'game_name' => 'Keno', 'api_game_id' => 'c311eb4bbba03b105d150504931f2479', 'api_game_code' => 'keno', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'mines', 'game_name' => 'Mines', 'api_game_id' => '5c4a12fb0a9b296d9b0d5f9e1cd41d65', 'api_game_code' => 'mines', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'mini-roulette', 'game_name' => 'Mini Roulette', 'api_game_id' => '9dc7ac6155c5a19c1cc204853e426367', 'api_game_code' => 'mini-roulette', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'plinko', 'game_name' => 'Plinko', 'api_game_id' => '6ab7a4fe5161936012d6b06143918223', 'api_game_code' => 'plinko', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'balloon', 'game_name' => 'Balloon', 'api_game_id' => 'de88f202c5a8beeaccabbd944f8acfbf', 'api_game_code' => 'balloon', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'multikeno', 'game_name' => 'Keno 80', 'api_game_id' => '7a762edbe411ebc9be416870a734bd03', 'api_game_code' => 'multikeno', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'trader', 'game_name' => 'Trader', 'api_game_id' => 'ad5973a7625b5d18257e64340fe22ca1', 'api_game_code' => 'trader', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
    array('local_game_uid' => '', 'provider_game_code' => 'crystal-fall', 'game_name' => 'Crystal Fall', 'api_game_id' => '8fa279cd15052eeffa7038df803f8c49', 'api_game_code' => 'crystal-fall', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Slot'),
    array('local_game_uid' => '', 'provider_game_code' => 'neo-vegas', 'game_name' => 'Neo Vegas', 'api_game_id' => '0f03d2c034a16431a9a4a2b0009c2203', 'api_game_code' => 'neo-vegas', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Slot'),
    array('local_game_uid' => '', 'provider_game_code' => 'gates-of-egypt', 'game_name' => 'Gates of Egypt', 'api_game_id' => '56d299921450cce8c4a07212cc5c64ca', 'api_game_code' => 'gates-of-egypt', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Slot'),
    array('local_game_uid' => '', 'provider_game_code' => 'pilot-chicken', 'game_name' => 'Pilot Chicken', 'api_game_id' => 'ef323466f031cc0d206fd20ca8149f42', 'api_game_code' => 'pilot-chicken', 'api_vendor_code' => 'spribe', 'api_provider_name' => 'Spribe', 'api_game_type' => 'Crash'),
);
